### ISSUE TITLE
关于decoder的initial_state问题

### ISSUE THREAD

**Issue by eecshope** [applenob/RNN-for-Joint-NLU#12]
老师好！我是一名大二学生，想问一下示例代码中decoder的initial_state为什么是zero_state。并且我在自己写代码时也发现encoder最后输出的state给decoder喂不进去，但我在手写luong的attention时是把encoder的final_state用作decoder的initial_state的。是不是我对这套attention的封装机制理解有问题？还望老师解答。

**Comment by NiceMartin** [comment]
关注。

**Comment by NiceMartin** [comment]
hi, 我修改成这样就可以了
     initial_state=out_cell.zero_state(
                dtype=tf.float32, batch_size=batch_size).clone(cell_state=encoder_final_state))

**Comment by eecshope** [comment]
嗯嗯，可以，但我阅读源码还没有读到这里，不知其合理性。共同学习非常感谢！
